### ISSUE TITLE
Toriptables2 not working with nmap inside Virtualbox

### ISSUE THREAD

**Issue by falcon758** [ruped24/toriptables2#10]
Expected Behavior

It was expected that nmap returned positive values which is not happening

Actual Behavior

It must be some iptables rules that is blocking the inbound or outbound communications
No errors are returned

Steps to Reproduce (including precondition)

Virtualbox in Bridge adapter
toriptables2.py -l
nmap -Pn {ip} -p {port} (-Pn since rules are blocking icmp)

Your Environment
    OS: Ubuntu
    toriptables2 version: last

**Comment by ruped24** [comment]
Toriptables  uses the application layer SOCKS4/SOCKS5 to route traffic through Tor. 
Non TCP/IP protocols are dropped such as ICMP.  Hence Nmap doesn't work.  Turn off ping -P0.

Those non tcp protocols will leak your original IP address. 

All application will make its TCP connections through Tor on port tcp/9040. See [here](https://superuser.com/questions/341946/can-i-ping-send-icmp-through-tor).
