### ISSUE TITLE
Errors Python...

### ISSUE THREAD

**Issue by S0rci3r** [ruped24/toriptables2#12]
Hi,

System Manjaro Linux 18.0.2
Kernel 4.18.20-1-MANJARO
Python2 2.7.15
iptables v1.8.2 (legacy)
Tor 0.3.4.9

I followed the tutorial https://en.kali.tools/?p=423 on BlackArch

**sudo python2 toriptables2.py -l**
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/bin/toriptables2.py", line 58, in restart_tor
    stdout=fnull, stderr=fnull)
  File "/usr/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/bin/toriptables2.py", line 58, in restart_tor
    stdout=fnull, stderr=fnull)
  File "/usr/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**sudo python2 /usr/local/bin/toriptables2.py -f**
 [!] Anonymizer status [OFF]

Thx

**Comment by ruped24** [comment]
Give this version a try.  This was fixed to work with Arch Linux.
https://github.com/bonanza123/toriptables2

Let me know if this one work.

**Comment by S0rci3r** [comment]
Thank you very much, we are making progress... but,

**sudo toriptables2.py -h**

 [+] Anonymizer status [ON]
 [*] Getting public IP, please wait...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
..............

**Comment by ruped24** [comment]
Try these: Error: Getting public IP
See under [Troubleshooting](https://github.com/ruped24/toriptables2/wiki/Troubleshooting):


Let me know if you are still getting the error.

**Comment by S0rci3r** [comment]
**sudo time curl -s http://ident.me/.json | python -c "import sys,json; sys.stdout.write(json.load(sys.stdin)['address'])"**
0.00user 0.00system 0:00.52elapsed 1%CPU (0avgtext+0avgdata 7712maxresident)k
344inputs+0outputs (1major+440minor)pagefaults 0swaps
xx.xxx.xx.xxx%  <=== my real ip is ok

**Comment by ruped24** [comment]
Purge and re-install _to_r.  Make sure the torrc is the one provided by the tor install.  Other anonymizers create their own torrc file.

**Comment by S0rci3r** [comment]
Yess ;-) it's fonctional...
I use the DNS of my VPN

**sudo toriptables2.py -l**
 [+] Anonymizer status [ON]
 [*] Getting public IP, please wait...
 [?] Still waiting for IP address...
 [+] Your IP is 66.146.193.33

Several questions  :
Thanks again, I noticed that the ip address changes very often is normal?
Can we change the time of the loop?
Can we run toriptables behind a vpn?

Sorry for my english... use deepL :p

**Comment by ruped24** [comment]
Tor changes IP between one and three minutes.
See Advance[ tweaks](https://github.com/ruped24/tor_ip_switcher/wiki/Troubleshooting) for geeks.

**Comment by S0rci3r** [comment]
Ok, Thank you again for your help and reactivity ;-)

**Comment by ruped24** [comment]
You are welcome :+1:

**Comment by Zicrys** [comment]
Hello, i have this problem:
[!] Can't get public ip address!
Exception KeyError: KeyError(140107305867072,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored

**Comment by Zicrys** [comment]
Hello! I have this problem:
 [!] Can't get public ip address!
Exception KeyError: KeyError(139968192689984,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
im reinstall this module, but problem is not resolved.

**Comment by ruped24** [comment]
> Hello! I have this problem: [!] Can't get public ip address! Exception KeyError: KeyError(139968192689984,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored im reinstall this module, but problem is not resolved.

I need more information.

**Comment by Zicrys** [comment]
> I think this error is due to the blockage in our country. All ip addresses are blocked, the site tor project does not work.

**Comment by ruped24** [comment]
> > I think this error is due to the blockage in our country. All ip addresses are blocked, the site tor project does not work.

Try setting your exit node.  See [here](https://github.com/ruped24/toriptables2/wiki/Troubleshooting#set-tor-exitnodes).

**Comment by CrazyHumster** [comment]
Hi i have same problem, but your answer dont help me(((
"time curl -s https://check.torproject.org/api/ip | python2 -c "import sys,json; sys.stdout.write(json.load(sys.stdin)['IP'])""

[+] Anonymizer status [ON]
[*] Getting public IP, please wait...
[?] Still waiting for IP address...
[?] Still waiting for IP address...
[?] Still waiting for IP address...
[?] Still waiting for IP address...
[?] Still waiting for IP address...
[?] Still waiting for IP address...
[?] Still waiting for IP address...
[?] Still waiting for IP address...
[?] Still waiting for IP address...
[?] Still waiting for IP address...

**Comment by ruped24** [comment]
> Hi i have same problem, but your answer dont help me((( "time curl -s https://check.torproject.org/api/ip | python2 -c "import sys,json; sys.stdout.write(json.load(sys.stdin)['IP'])""
> 
> [+] Anonymizer status [ON] [*] Getting public IP, please wait... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address...

I need more information:
What distro are you using.

**Comment by ruped24** [comment]
First flush the tables:
sudo toriptables2 -f

What is the results when you run:
"time curl -s  https://check.torproject.org/api/ip | python2 -c "import sys,json; sys.stdout.write(json.load(sys.stdin)['IP'])"

**Comment by Zicrys** [comment]
Script don’t work (
bash: синтаксическая ошибка рядом с неожиданным маркером «json.load»
  
>Пятница, 4 февраля 2022, 16:54 +04:00 от Rupert Edwards ***@***.***>:
> 
> 
>First flush the tables:
>sudo toriptables2 -f
>What is the results when you run:
>"time curl -s  https://check.torproject.org/api/ip | python2 -c "import sys,json; sys.stdout.write(json.load(sys.stdin)['IP'])"
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you commented. Message ID:  <ruped24/toriptables2/issues/12/1029960596 @ github . com> 
 
 
--
С уважением, Антон.

**Comment by ruped24** [comment]
> Script don’t work ( bash: синтаксическая ошибка рядом с неожиданным маркером «json.load»  
> Пятница, 4 февраля 2022, 16:54 +04:00 от Rupert Edwards ***@***.***>:     First flush the tables: sudo toriptables2 -f What is the results when you run: "time curl -s https://check.torproject.org/api/ip | python2 -c "import sys,json; sys.stdout.write(json.load(sys.stdin)['IP'])" — Reply to this email directly, view it on GitHub , or unsubscribe . Triage notifications on the go with GitHub Mobile for iOS or Android . You are receiving this because you commented. Message ID: <ruped24/toriptables2/issues/12/1029960596 @ github . com>
>     -- С уважением, Антон.

Try toriptables3.
Let me know if it work or post error here.

**Comment by Zicrys** [comment]
Does not work( And it doesn't give any errors:
sudo toriptables3.py -l
 [+] Anonymizer status [ON]
 [*] Getting public IP, please wait...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
~/toriptables3$

**Comment by CrazyHumster** [comment]
> > Hi i have same problem, but your answer dont help me((( "time curl -s https://check.torproject.org/api/ip | python2 -c "import sys,json; sys.stdout.write(json.load(sys.stdin)['IP'])""
> > [+] Anonymizer status [ON] [*] Getting public IP, please wait... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address...
> 
> I need more information: What distro are you using.

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by ruped24** [comment]
> > > Hi i have same problem, but your answer dont help me((( "time curl -s https://check.torproject.org/api/ip | python2 -c "import sys,json; sys.stdout.write(json.load(sys.stdin)['IP'])""
> > > [+] Anonymizer status [ON] [*] Getting public IP, please wait... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address...
> > 
> > 
> > I need more information: What distro are you using.
> 
> DISTRIB_ID=Ubuntu DISTRIB_RELEASE=20.04 DISTRIB_CODENAME=focal DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS" NAME="Ubuntu" VERSION="20.04.3 LTS (Focal Fossa)" ID=ubuntu ID_LIKE=debian PRETTY_NAME="Ubuntu 20.04.3 LTS" VERSION_ID="20.04" HOME_URL="https://www.ubuntu.com/" SUPPORT_URL="https://help.ubuntu.com/" BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/" PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy" VERSION_CODENAME=focal UBUNTU_CODENAME=focal

OK;
Try:
sudo toriptables3.py -f

sudo toriptables3.py -i  

Let me know the results..

**Comment by CrazyHumster** [comment]
> > > > Hi i have same problem, but your answer dont help me((( "time curl -s https://check.torproject.org/api/ip | python2 -c "import sys,json; sys.stdout.write(json.load(sys.stdin)['IP'])""
> > > > [+] Anonymizer status [ON] [*] Getting public IP, please wait... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address...
> > > 
> > > 
> > > I need more information: What distro are you using.
> > 
> > 
> > DISTRIB_ID=Ubuntu DISTRIB_RELEASE=20.04 DISTRIB_CODENAME=focal DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS" NAME="Ubuntu" VERSION="20.04.3 LTS (Focal Fossa)" ID=ubuntu ID_LIKE=debian PRETTY_NAME="Ubuntu 20.04.3 LTS" VERSION_ID="20.04" HOME_URL="https://www.ubuntu.com/" SUPPORT_URL="https://help.ubuntu.com/" BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/" PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy" VERSION_CODENAME=focal UBUNTU_CODENAME=focal
> 
> OK; Try:
> 
> 1. sudo toriptables3.py --flush
> 2. sudo toriptables3.py --ip
> 
> Let me know the results...

sudo toriptables3.py --flush
[sudo] пароль для crazyhumster: 
sudo: toriptables3.py: команда не найдена

**Comment by CrazyHumster** [comment]
> > > > Hi i have same problem, but your answer dont help me((( "time curl -s https://check.torproject.org/api/ip | python2 -c "import sys,json; sys.stdout.write(json.load(sys.stdin)['IP'])""
> > > > [+] Anonymizer status [ON] [*] Getting public IP, please wait... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address...
> > > 
> > > 
> > > I need more information: What distro are you using.
> > 
> > 
> > DISTRIB_ID=Ubuntu DISTRIB_RELEASE=20.04 DISTRIB_CODENAME=focal DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS" NAME="Ubuntu" VERSION="20.04.3 LTS (Focal Fossa)" ID=ubuntu ID_LIKE=debian PRETTY_NAME="Ubuntu 20.04.3 LTS" VERSION_ID="20.04" HOME_URL="https://www.ubuntu.com/" SUPPORT_URL="https://help.ubuntu.com/" BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/" PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy" VERSION_CODENAME=focal UBUNTU_CODENAME=focal
> 
> OK; Try:
> 
> 1. sudo toriptables3.py --flush
> 2. sudo toriptables3.py --ip
> 
> Let me know the results...

sudo toriptables3.py --flush
sudo: toriptables3.py: команда не найдена

**Comment by ruped24** [comment]
> команда не найдена
sudo chmod +x toriptables3.py

sudo ./toriptables3.py --flush
sudo ./toriptables3.py --ip

Let me know...

**Comment by CrazyHumster** [comment]
> > команда не найдена
> > sudo chmod +x toriptables3.py
> 
> sudo ./toriptables3.py --flush sudo ./toriptables3.py --ip
> 
> Let me know...

Same
sudo ./toriptables3.py --flush
sudo: ./toriptables3.py: команда не найдена

**Comment by ruped24** [comment]
> Does not work( And it doesn't give any errors: sudo toriptables3.py -l [+] Anonymizer status [ON] [*] Getting public IP, please wait... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... ~/toriptables3$

Run the same command but change to -f.
Then run the same command with -i.

**Comment by CrazyHumster** [comment]
> > Does not work( And it doesn't give any errors: sudo toriptables3.py -l [+] Anonymizer status [ON] [*] Getting public IP, please wait... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... ~/toriptables3$
> 
> Run the same command but change to -f. Then run the same command with -i.

toriptables3.py -f
toriptables3.py: команда не найдена
crazyhumster@crazyhumster-VirtualBox:~$ toriptables2.py -l
Fatal: can't open lock file /run/xtables.lock: Permission denied
Fatal: can't open lock file /run/xtables.lock: Permission denied
Fatal: can't open lock file /run/xtables.lock: Permission denied
Fatal: can't open lock file /run/xtables.lock: Permission denied
owner: Could not determine whether revision 1 is supported, assuming it is.
owner: Could not determine whether revision 1 is supported, assuming it is.
Fatal: can't open lock file /run/xtables.lock: Permission denied
Fatal: can't open lock file /run/xtables.lock: Permission denied
Fatal: can't open lock file /run/xtables.lock: Permission denied
Fatal: can't open lock file /run/xtables.lock: Permission denied
Fatal: can't open lock file /run/xtables.lock: Permission denied
Fatal: can't open lock file /run/xtables.lock: Permission denied
Fatal: can't open lock file /run/xtables.lock: Permission denied
Fatal: can't open lock file /run/xtables.lock: Permission denied
conntrack: Could not determine whether revision 1 is supported, assuming it is.
conntrack: Could not determine whether revision 2 is supported, assuming it is.
conntrack: Could not determine whether revision 3 is supported, assuming it is.
conntrack: Could not determine whether revision 3 is supported, assuming it is.
conntrack: Could not determine whether revision 3 is supported, assuming it is.
conntrack: Could not determine whether revision 2 is supported, assuming it is.
Fatal: can't open lock file /run/xtables.lock: Permission denied
Fatal: can't open lock file /run/xtables.lock: Permission denied
Fatal: can't open lock file /run/xtables.lock: Permission denied
Fatal: can't open lock file /run/xtables.lock: Permission denied
Fatal: can't open lock file /run/xtables.lock: Permission denied
Fatal: can't open lock file /run/xtables.lock: Permission denied
owner: Could not determine whether revision 1 is supported, assuming it is.
owner: Could not determine whether revision 1 is supported, assuming it is.
Fatal: can't open lock file /run/xtables.lock: Permission denied
Fatal: can't open lock file /run/xtables.lock: Permission denied
 [+] Anonymizer status [ON]
 [*] Getting public IP, please wait...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...

**Comment by CrazyHumster** [comment]
> > Does not work( And it doesn't give any errors: sudo toriptables3.py -l [+] Anonymizer status [ON] [*] Getting public IP, please wait... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... ~/toriptables3$
> 
> Run the same command but change to -f. Then run the same command with -i.

toriptables2.py -i
 [*] Getting public IP, please wait...
 [?] Still waiting for IP address...

**Comment by ruped24** [comment]
> > > Does not work( And it doesn't give any errors: sudo toriptables3.py -l [+] Anonymizer status [ON] [*] Getting public IP, please wait... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... [?] Still waiting for IP address... ~/toriptables3$
> > 
> > 
> > Run the same command but change to -f. Then run the same command with -i.
> 
> toriptables2.py -f Fatal: can't open lock file /run/xtables.lock: Permission denied Fatal: can't open lock file /run/xtables.lock: Permission denied [!] Anonymizer status [OFF] toriptables2.py -i [*] Getting public IP, please wait... [?] Still waiting for IP address... [?] Still waiting for IP address...

1. It maybe your Country blocking Tor.  I don't know from here.
2. What I suggest to try is autovpn2 then run toriptables2 to try and by pass your country filter. :(
3. Try running/testing it in a Kali VM.

PS. Time is my enemy right now ... unfortunately I can't spend anymore time on this.
