### ISSUE TITLE
Could not find platform

### ISSUE THREAD

**Issue by KaliLinuxPentest** [ruped24/toriptables2#15]
toriptables2.py 
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site

What is about? 2 hours wasted for this error...

**Comment by ruped24** [comment]
I need more information.
What platform are you using?  Linux?  What distro?

**Comment by ruped24** [comment]
> toriptables2.py
> Could not find platform independent libraries 
> Could not find platform dependent libraries <exec_prefix>
> Consider setting $PYTHONHOME to [:<exec_prefix>]
> ImportError: No module named site
> 
> What is about? 2 hours wasted for this error...

https://iguana.cdn.livenewschat.eu/hls/cnnus_live/index.m3u8

**Comment by ruped24** [comment]
> toriptables2.py
> Could not find platform independent libraries 
> Could not find platform dependent libraries <exec_prefix>
> Consider setting $PYTHONHOME to [:<exec_prefix>]
> ImportError: No module named site
> 
> What is about? 2 hours wasted for this error...

I need more information.
What platform are you using? Linux? What distro?

**Comment by KaliLinuxPentest** [comment]
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2020.2
Codename:	kali-rolling

**Comment by KaliLinuxPentest** [comment]
> I need more information.
> What platform are you using? Linux? What distro?

Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2020.2
Codename:	kali-rolling

**Comment by ruped24** [comment]
> > I need more information.
> > What platform are you using? Linux? What distro?
> 
> Distributor ID:	Kali
> Description:	Kali GNU/Linux Rolling
> Release:	2020.2
> Codename:	kali-rolling

What python version:
type: python --version

**Comment by KaliLinuxPentest** [comment]
> > > I need more information.
> > > What platform are you using? Linux? What distro?
> > 
> > 
> > Distributor ID:	Kali
> > Description:	Kali GNU/Linux Rolling
> > Release:	2020.2
> > Codename:	kali-rolling
> 
> What python version:
> type: python --version

Python 3.7.7

**Comment by KaliLinuxPentest** [comment]
May be it because i use 2nd and 3d version python together?

**Comment by ruped24** [comment]
> May be it because i use 2nd and 3d version python together?
Let's see if python 2.7 is installed:
type: /usr/bin/env python2

**Comment by KaliLinuxPentest** [comment]
> > May be it because i use 2nd and 3d version python together?
> > Let's see if python 2.7 is installed:
> > type: /usr/bin/env python2

Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site

**Comment by ruped24** [comment]
Try running it with: python2 ./toriptables2

**Comment by KaliLinuxPentest** [comment]
> Try running it with:` python2 ./toriptables2`

Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site

Nothing is changed

**Comment by KaliLinuxPentest** [comment]
how can I used this on python3?

**Comment by ruped24** [comment]
> > > May be it because i use 2nd and 3d version python together?
> > > Let's see if python 2.7 is installed:
> > > type: /usr/bin/env python2
> 
> Could not find platform independent libraries 
> Could not find platform dependent libraries <exec_prefix>
> Consider setting $PYTHONHOME to [:<exec_prefix>]
> ImportError: No module named site
> Strange because today I reinstalled python2 with pip3 command

> > Try running it with:` python2 ./toriptables2`
> 
> Could not find platform independent libraries 
> Could not find platform dependent libraries <exec_prefix>
> Consider setting $PYTHONHOME to [:<exec_prefix>]
> ImportError: No module named site
> 
> Nothing is changed

Do you have python2.7 installed?
Did you run  `/usr/bin/env python2` ?
You should get the python prompt.

**Comment by KaliLinuxPentest** [comment]
> > > > May be it because i use 2nd and 3d version python together?
> > > > Let's see if python 2.7 is installed:
> > > > type: /usr/bin/env python2
> > 
> > 
> > Could not find platform independent libraries
> > Could not find platform dependent libraries <exec_prefix>
> > Consider setting $PYTHONHOME to [:<exec_prefix>]
> > ImportError: No module named site
> > Strange because today I reinstalled python2 with pip3 command
> 
> > > Try running it with:` python2 ./toriptables2`
> > 
> > 
> > Could not find platform independent libraries
> > Could not find platform dependent libraries <exec_prefix>
> > Consider setting $PYTHONHOME to [:<exec_prefix>]
> > ImportError: No module named site
> > Nothing is changed
> 
> Do you have python2.7 installed?
> Did you run `/usr/bin/env python2` ?
> You should get the python prompt.

pip3 install python2
Requirement already satisfied: python2 in /usr/local/lib/python3.8/dist-packages (1.2)

**Comment by ruped24** [comment]
I can compile 

> > > > > May be it because i use 2nd and 3d version python together?
> > > > > Let's see if python 2.7 is installed:
> > > > > type: /usr/bin/env python2
> > > 
> > > 
> > > Could not find platform independent libraries
> > > Could not find platform dependent libraries <exec_prefix>
> > > Consider setting $PYTHONHOME to [:<exec_prefix>]
> > > ImportError: No module named site
> > > Strange because today I reinstalled python2 with pip3 command
> > 
> > 
> > > > Try running it with:` python2 ./toriptables2`
> > > 
> > > 
> > > Could not find platform independent libraries
> > > Could not find platform dependent libraries <exec_prefix>
> > > Consider setting $PYTHONHOME to [:<exec_prefix>]
> > > ImportError: No module named site
> > > Nothing is changed
> > 
> > 
> > Do you have python2.7 installed?
> > Did you run `/usr/bin/env python2` ?
> > You should get the python prompt.
> 
> pip3 install python2
> Requirement already satisfied: python2 in /usr/local/lib/python3.8/dist-packages (1.2)

You have messed up the python2 install with pip3.  
1.unintall it with pip3.
2. apt install python2

**Comment by ruped24** [comment]
I can compile you a binary to run on Python3 if you like.
Let me know.

**Comment by KaliLinuxPentest** [comment]
> I can compile you a binary to run on Python3 if you like.
> Let me know.

What different between?

**Comment by KaliLinuxPentest** [comment]
> > I can compile you a binary to run on Python3 if you like.
> > Let me know.
> 
> What difference between?

**Comment by KaliLinuxPentest** [comment]
> I can compile you a binary to run on Python3 if you like.
> Let me know.

Yes, i am trying this

**Comment by ruped24** [comment]
> > > I can compile you a binary to run on Python3 if you like.
> > > Let me know.
> > 
> > 
> > What difference between?

The binary is python independent.  No python interpreter installation needed.

**Comment by ruped24** [comment]
I'll compile you a binary and give you the link and instructions.  Give me a few...  within the hour.

**Comment by KaliLinuxPentest** [comment]
> I'll compile you a binary and give you the link and instructions. Give me a few... within the hour.

Okey

**Comment by ruped24** [comment]
> > I'll compile you a binary and give you the link and instructions. Give me a few... within the hour.
> 
> Okey

Here is the link: http://5afccc2a7e12.ngrok.io
1.  Download the file, then unzip
2. cd into the projects directory
3. sudo ./toriptables2 or cd into directory Toriptables2 ./toriptables2

Let me know if it work.  Then will move it to /usr/local/bin

**Comment by KaliLinuxPentest** [comment]
> > > I'll compile you a binary and give you the link and instructions. Give me a few... within the hour.
> > 
> > 
> > Okey
> 
> Here is the link: http://5afccc2a7e12.ngrok.io
> 
> 1. Download the file, then unzip
> 2. cd into the projects directory
> 3. sudo ./toriptables2 or cd into directory Toriptables2 ./toriptables2
> 
> Let me know if it work. Then will move it to /usr/local/bin

Its working! TNX! What i must move? Only toriptables2.py?

**Comment by ruped24** [comment]
> > > > I'll compile you a binary and give you the link and instructions. Give me a few... within the hour.
> > > 
> > > 
> > > Okey
> > 
> > 
> > Here is the link: http://5afccc2a7e12.ngrok.io
> > 
> > 1. Download the file, then unzip
> > 2. cd into the projects directory
> > 3. sudo ./toriptables2 or cd into directory Toriptables2 ./toriptables2
> > 
> > Let me know if it work. Then will move it to /usr/local/bin
> 
> Its working! TNX! What i must move? Only toriptables2.py?

OK.
1. `sudo mv Toriptables2 /usr/local/bin`
2. `cd /usr/local/bin`
3. `sudo ln -s Toriptables2/toriptables2 ./
`

**Comment by KaliLinuxPentest** [comment]
[+] Anonymizer status [ON]
 [*] Getting public IP, please wait...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
[+] Anonymizer status [ON]
 [*] Getting public IP, please wait...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
 [?] Still waiting for IP address...
[+] Your IP is 
Its ok but longer than before remove to /bin

**Comment by ruped24** [comment]
OK. Let me explain. You are missing a library.
The binary is in the Toriptables2 folder along with it's compiled libs. You MUST have the toriptables2 file there.

Create a sym link as I showed in the above instructions.

**Comment by ruped24** [comment]
Let me compile it down to one file for you.  Give me a few.

**Comment by ruped24** [comment]
OK. 
Link here:  http://5afccc2a7e12.ngrok.io 
1. Delete the old files and folder.
2. Download this single binary
3. Run `sudo ./toriptables2`

**Comment by ruped24** [comment]
Let me know if it work. Then I'll upload it to release so others with the same python3.x problems can run this binary instead of fight with 2to3, grrrr.

**Comment by KaliLinuxPentest** [comment]
> OK.
> Link here: http://5afccc2a7e12.ngrok.io
> 
> 1. Delete the old files and folder.
> 2. Download this single binary
> 3. Run `sudo ./toriptables2`

Tnx!

**Comment by ruped24** [comment]
Did it work?
The first on or the second one?
What did you do to fix it?

Thx

**Comment by ruped24** [comment]
> > OK.
> > Link here: http://5afccc2a7e12.ngrok.io
> > 
> > 1. Delete the old files and folder.
> > 2. Download this single binary
> > 3. Run `sudo ./toriptables2`
> 
> Tnx!

Did it work?
The first one or the second one?
What did you do to fix it?

Thx
