### ISSUE TITLE
hello，Whether its traffic is exported through the local IP or through an openwrt proxy already running as a link router, such as ssr v2r vpn

### ISSUE THREAD

**Issue by hello-2020-hello** [ruped24/toriptables2#16]
Whether its traffic is exported through the local IP or through an openwrt proxy already running as a link router, such as ssr v2r vpn
它的流量是通过本地IP导出还是通过已经作为链接路由器运行的openwrt代理（例如ssr v2r vpn）导出

**Comment by ruped24** [comment]
> Whether its traffic is exported through the local IP or through an openwrt proxy already running as a link router, such as ssr v2r vpn
> 它的流量是通过本地IP导出还是通过已经作为链接路由器运行的openwrt代理（例如ssr v2r vpn）导出

I don't understand your question. Do you have a problem with toriptables2?  What distro?
