### ISSUE TITLE
Activation of network connection failed.

### ISSUE THREAD

**Issue by MadHouser** [ruped24/toriptables2#18]
After using toriptables2 shortly after I started getting error activation of network connection failed. Any fixes for that? I am also experiencing issues with network connections, I have issues with wired and internal wireless connections, they disconnect and reconnect and the only thing keeping me online is my external adapter. It also takes a few tries to check for updates as seen in the ss that's what I get.

![Screenshot from 2020-08-25 15-36-32](https://user-images.githubusercontent.com/19828315/91188145-dfd06880-e6e8-11ea-925d-a9674e41cfc6.png)

![Screenshot from 2020-08-25 15-29-41](https://user-images.githubusercontent.com/19828315/91187265-e6aaab80-e6e7-11ea-8fda-93044d9f3e28.png) Im also getting this as well.

**Comment by ruped24** [comment]
> After using toriptables2 shortly after I started getting error activation of network connection failed. Any fixes for that? I am also experiencing issues with network connections, I have issues with wired and internal wireless connections, they disconnect and reconnect and the only thing keeping me online is my external adapter. It also takes a few tries to check for updates as seen in the ss that's what I get.
> 
> ![Screenshot from 2020-08-25 15-36-32](https://user-images.githubusercontent.com/19828315/91188145-dfd06880-e6e8-11ea-925d-a9674e41cfc6.png)
> 
> ![Screenshot from 2020-08-25 15-29-41](https://user-images.githubusercontent.com/19828315/91187265-e6aaab80-e6e7-11ea-8fda-93044d9f3e28.png) Im also getting this as well.

Does it connect to the Tor network?
What distro are you using?
