### ISSUE TITLE
ping problem

### ISSUE THREAD

**Issue by SongulKizilay** [ruped24/toriptables2#19]
I'm having trouble pinging after using toriptables2. it fixes when i turn it off

**Comment by ruped24** [comment]
See [here]( https://github.com/ruped24/toriptables2/issues/10). 
Toriptables uses TCP/ip application layer to route traffic SOCKS4/SOCKS5 aware applications through Tor.
Non TCP/IP protocols are dropped such as ICMP. Hence Nmap doesn't work.

Those non tcp protocols will leak your original IP address.

All application will make its TCP connections through Tor on port tcp/9040. See [here](https://superuser.com/questions/341946/can-i-ping-send-icmp-through-tor).
