### ISSUE TITLE
 [!] Can't get public ip address!

### ISSUE THREAD

**Issue by dorogarcia** [ruped24/toriptables2#2]
Hello,

Your script works good but sometimes shows an error:

root@kali:~# toriptables2 -l
 [+] Anonymizer status [ON]
 [*] Getting public IP, please wait ...
 [!] Can't get public ip address!
root@kali:~# toriptables2 -l
 [+] Anonymizer status [ON]
 [*] Getting public IP, please wait ...
 [!] Can't get public ip address!
root@kali:~# toriptables2 -l
 [+] Anonymizer status [ON]
 [*] Getting public IP, please wait ...
 [+] Your IP is XXX.XXX.XXX.XXX
root@kali:~# toriptables2 -l
 [+] Anonymizer status [ON]
 [*] Getting public IP, please wait ...
 [!] Can't get public ip address!
root@kali:~#

The problem is that sometimes can not validate tor IP but it creates iptables rules and works.

Regards!

**Comment by ruped24** [comment]
> ### The problem is that sometimes can not validate tor IP but it creates iptables rules and works.

### That is caused for a couple of reasons:
1. The tor node maybe slow, so it timeout fetching IP public address. It's using the tor's DNS to resolve .
2. Your connection speed:  Example wire vs. wireless.  Latency may cause a timeout while trying to fetch the public IP.
3.  The error should accurately say slow node.

Try: Flush and then  reload.  If persist,  see 1 or 2 above.

The rules will always get load. Hence your are Anonymized.  
You can ignore "Can't get public ip address". I't not really an error.

Technical note: The script make two fetch attempts before timing-out.

**Comment by dorogarcia** [comment]
I think the problem is starting tor service take few seconds more than your script wait, but everything works ;)

**Comment by ruped24** [comment]
Thanks for the feedback.  Can I close the issue?
