### ISSUE TITLE
toriptables2 linux mint

### ISSUE THREAD

**Issue by vladisgit** [ruped24/toriptables2#20]
In case of "   Still waiting for IP address..." trying to launch a toriptables2 on linux mint- just turn the Gufw Firewall off, as i did, and its working now. Feel free to get in contact with me on the email: vladis72@mail.ru

**Comment by ruped24** [comment]
> In case of " Still waiting for IP address..." trying to launch a toriptables2 on linux mint- just turn the Gufw Firewall off, as i did, and its working now. Feel free to get in contact with me on the email: [vladis72@mail.ru](mailto:vladis72@mail.ru)

I don't know you Geo location.
Try: toriptables2 -f
Then: toriptables2 --ip

Make sure you have tor installed.  apt install tor.

See if you get your WAN IP back.
