### ISSUE TITLE
Leak prevention with --ctstate/state  INVALID

### ISSUE THREAD

**Issue by sssseossss** [ruped24/toriptables2#7]
Hi,
thanks for the script!
can you comment, why didn't you put leak prevention with 
cstate and state like this:
iptables -A OUTPUT -m conntrack --ctstate INVALID -j DROP
iptables -A OUTPUT -m state --state INVALID -j DROP
as per this warning: https://lists.torproject.org/pipermail/tor-talk/2014-March/032507.html
thanks!

**Comment by ruped24** [comment]
Hi,
1. After studying the rule.  I determined that dropping Invalid packets on the Output chain after you have Related, Established -- wasn't necessary (from my point of view)
2. Connection Tracking may not be compiled in some custom kernel.  I know it should be.

Let me know if you can reproduce any leakage.

Thanks for asking.

Closing
